### ISSUE TITLE
Request for add component u8g2 (IEC-263)

### ISSUE THREAD

**Issue by shishirong** [espressif/idf-extra-components#474]

**Comment by suda-morris** [comment]
I think there's some in the community, e.g. https://github.com/mkfrey/u8g2-hal-esp-idf/tree/master

**Comment by shishirong** [comment]
如果添加到idf-extra-components，就可以直接使用idf_component.yml 来添加依赖，会方便很多。
后来我发现，非idf-extra-components的也可以通过下面这种方式添加，也就无所谓了。
```yaml
dependencies:
  idf:
    version: ">=5.3.2"
  u8g2:
    version: 'f0eb0ed7bfc0f1da99f2899d2312538ac9929ac7'
    git: 'https://github.com/olikraus/u8g2.git'
```
